### ISSUE TITLE
bug with MODISGrid function

### ISSUE THREAD

**Issue by earthcli** [seantuck12/MODISTools#21] opened 2016-01-02 06:19 UTC
The MODISGrid function break when there is incomplete line in asc file created by the MODISSubsets file.
the incomplete line in the asc file is :9,9,11362049.40,3334924.97,231.656358264,character(0)
while a complete line may as:
9,9,11362049.40,3334924.97,231.656358264,MOD13Q1.A2015033.h28v06.005.2015050082510.250m_16_days_NDVI,MOD13Q1,A2015033,Lat30Lon118Samp9Line9,2015050082510,6882,6991,6817,6656,6568

Error in MODISGrid(DirName = products, SubDir = FALSE, NoDataValues = nodatavalues) : 
  Mismatch between NoDataValues and data products found in files.

**Comment by seantuck12** [comment] 2016-01-02 19:58
Thanks for highlighting this. The incomplete line is an incompletely downloaded subset from your call to `MODISSubsets`. Could you help me to understand the issue by showing your call to `MODISSubsets` please? It is possible that one subset was not properly retrieved due to some temporary error with the web service. If so, retrying the download once more should produce a complete subset and solve the problem. It is also possible that no subset data were downloaded for that location because those data do not exist, perhaps because it is not on land. Either way, the issue is to do with an incomplete subset from `MODISSubsets` rather than the `MODISGrid` function. That said, I have added another error check for missing data to produce a more informative error message.

**Comment by earthcli** [comment] 2016-01-03 04:06
Thanks you very much for your reply. My script is as follows:

require(MODISTools)
mysubset=structure(list(lat = c(30, 31, 32), long = c(118, 119, 120), 
    start.date = structure(c(1420070400, 1420070400, 1420070400
    ), class = c("POSIXct", "POSIXt"), tzone = "UTC"), end.date = structure(c(1433030400, 
    1433030400, 1433030400), class = c("POSIXct", "POSIXt"), tzone = "UTC"), 
    ID = structure(1:3, .Label = c("Lat30Lon118Start2015-01-01End2015-05-31", 
    "Lat31Lon119Start2015-01-01End2015-05-31", "Lat32Lon120Start2015-01-01End2015-05-31"
    ), class = "factor")), .Names = c("lat", "long", "start.date", 
"end.date", "ID"), row.names = c(NA, -3L), class = "data.frame")

MODISSubsets(mysubset,StartDate=TRUE,Size=c(1,1),Products="MOD13Q1",Bands=c("250m_16_days_EVI","250m_16_days_NDVI"))



and I found another bug about function Qualitycheck when processing MOD09A1 data.
because the colnum "MOD09A1" in data.frame QA_RANGE you have create in the function is a factor class, while 'QualityScores < QA_RANGE[1,Product]' require a numeric class.
which will result in an error in line "if(any((QualityScores < QA_RANGE[1,Product] | QualityScores > QA_RANGE[2,Product]) & QualityScores != QA_RANGE[3,Product]))",

Thanks again!

**Comment by seantuck12** [comment] 2016-02-06 16:13
I've pushed a fix now. The problematic download was empty because MOD13Q1 data do not exist for this date. Having an empty subset was causing bugs downstream. Now `MODISSubsets` will remove any problematic dates from the download, notifying the user with warning messages and a helpful status in the download log. `MODISGrid` then works as normal.

I've also pushed a fix for the `QualityCheck` bug. Thanks for pointing them out.

**Closed** 2016-02-17 15:54 UTC
